inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - "db/schema.rb"
    - "db/migrate/**/*"
    - "bin/**/*"
    - "vendor/**/*"

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Metrics/ParameterLists:
  Max: 8
